### ISSUE TITLE
#1: User can see their car

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] use css to set background of page
- [x] get image of car
- [x] add image to page
- [x] adjust image so it is seen at the top left corner of page
