### ISSUE TITLE
#2: User can turn their car

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add css classes to rotate car (up, down, left, right)
- [x] create data model to indicate which direction car is facing
- [x] add event listeners for arrow keys to rotate car when pressed
