### ISSUE TITLE
#3: User can start their car

### ISSUE THREAD

**Issue by moniquechang** [moniquechang/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] update data model to include location of car on page
- [ ] change position property of car
- [ ] add keydown event to move car
